name: "test"

on:
  push:
    branches: main

jobs:
  setup-node-pnpm:
    uses: ghdtjgus76/github-action-test/.github/workflows/setup-node-pnpm.yml@main
  test:
    runs-on: ubuntu-latest
    needs: setup-node-pnpm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Tests
        run: pnpm test
        working-directory: packages/wow-ui
